### PR TITLE
Remove: Stale documentation in Route.hx

### PR DESCRIPTION
**Pull request by loskool**

### CODE REVIEW

**Comment by joshtynjala** [comment]
What makes you think that this documentation is stale?

**Comment by joshtynjala** [comment]
For reference, the hn-reader sample includes an example of using named parameters:

https://github.com/feathersui/feathersui-openfl/blob/master/samples/hn-reader/src/com/feathersui/hn/views/ReaderView.hx#L60-L65

**Comment by loskool** [comment]
cool. 

Where is the IRouteView interface?

**Comment by joshtynjala** [comment]
Ah yes, the specific mention of `IRouteView` interface is indeed incorrect. It seems that I was considering adding that interface during the design phase, and I didn't update the docs afterwards after I decided not to add it.

The `updateState` property on `Route` is the correct way to access the named parameters. You pass it a function with two parameters, one for the view, and one for a `RouteState`. The `RouteState` contains the named parameters and some other relevant data, and you can pass whatever you need to the view.

```haxe
route.updateState = (view, routeState) -> {
	view.itemID = routeState.params.get("id");
}
```

You can also pass it as an argument to `Route.withClass()` and other methods for creating a route.

**Comment by joshtynjala** [comment]
I tweaked the docs a bit here: 48a7660b27689381d7b6cd2a69a84dd1537e60bc

**Comment by loskool** [comment]
Thanks for the example!

**Pull request closed without merging**
